# Generated by Django 3.1.10 on 2021-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0040_cloud_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_exchange_notified',
            field=models.BooleanField(default=False),
        ),
    ]
