# Generated by Django 3.1.13 on 2021-09-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0041_task_is_exchange_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='job',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolver',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='job',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
