# Generated by Django 3.1.13 on 2021-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_delete_review_issue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='address',
            field=models.CharField(default='', max_length=44),
        ),
    ]
