# Generated by Django 3.1.13 on 2021-10-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_task_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
