# Generated by Django 3.1.13 on 2021-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0044_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_annotation_mode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
