# Generated by Django 3.1.10 on 2021-06-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToWallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('human_wallet', models.CharField(default=False, max_length=42)),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
